### ISSUE TITLE
Expired token to download the data.zip

### ISSUE THREAD

**Issue by apssouza22** [thiagodma/Pytorch_exs#2]
Getting this error when accessing the link

<Error>
<Code>ExpiredToken</Code>
<Message>The provided token has expired.</Message>
<Details>Request signature expired at: 2020-05-19T20:09:39+00:00</Details>
</Error>

**Comment by thiagodma** [comment]
You have to get a new link on kaggle.

Go to [kaggle](https://www.kaggle.com/jangedoo/utkface-new), sign in, hit the download button and get the new generated link. 

Another option is to use the kaggle cli: `kaggle datasets download -d jangedoo/utkface-new`

**Comment by apssouza22** [comment]
Thanks for responding. 

Here is the fix if anyone else faces the issue.

Make sure you generate a new API token for Kaggle `kaggle.json`
```
! pip install -q kaggle
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download jangedoo/utkface-new  --unzip

```
