### ISSUE TITLE
Runtime error during training on Colab

### ISSUE THREAD

**Issue by apssouza22** [thiagodma/Pytorch_exs#3]
Do you have any idea how to fix this runtime issue?

```
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

Here some description for the issue https://programmerah.com/solved-runtimeerror-cuda-error-device-side-assert-triggered-30474/

**Comment by apssouza22** [comment]
I am trying to run it on Colab https://colab.research.google.com/github/thiagodma/Pytorch_exs/blob/master/MultiTaskLearning/multitask_age_gender_ethnicity_resnet34.ipynb#scrollTo=i7Vhz2rG9irt

**Comment by thiagodma** [comment]
On the [medium post](https://towardsdatascience.com/multi-task-learning-with-pytorch-and-fastai-6d10dc7ce855) I mention that you need to delete image 61_3_20170109150557335.jpg. Seems like this is a broken image. Try doing that and the problem should be solved

**Comment by apssouza22** [comment]
In the Github version, you have that as well. So that is not the problem. 

If anyone else is facing issues when running this example I have run through hell to build a multitask model. I hope I save some people time with this ready to run on Colab example https://github.com/apssouza22/cnn-for-devs/blob/master/i-multitask-model.ipynb

**Comment by HarshVardhanGoyal** [comment]
It is because of that file, one of the observations will have an out-of-bound class label and hence breaks the code. Great notebook, thanks
